### ISSUE TITLE
How to use this tool if my number of columns after splitting is not a constant value?

### ISSUE THREAD

**Issue by lfh19961021** [Advitya17/AutoBrickify#2]
This is a great tool to automate the conversion steps, 
but when I try to convert my point labels from BMS, 
it's not working if my point labels column able to split into different numbers of column
Here is part of my point label:
![image](https://user-images.githubusercontent.com/57752031/109971098-cad83000-7d30-11eb-9984-55ca921ea8c1.png)

My data-params.json:
```
{
    "fp": "data/Building.csv",
    
    "point_label_col": "ObjectName",
    
    "delimiter": { 
        "pattern": ".", 
        "regex": false 
    },
    
    "point_label_format": ["UpstreamAHU", "VAVName", "BrickClass"],
    
    "additional_brick_class_info_columns": [],

    "drop_null_rows": true
}
```
Some column will split into 2 columns, some 3, and some 4........
What point_label_format should I set if my number of columns after splitting is not a constant value?

**Comment by Advitya17** [comment]
@lfh19961021 thanks for the question! Could you describe the use cases on what the elements are supposed to mean if the columns are split into variable number of elements?

In our current implementation, we assume the point labels are supposed to be split into a uniform number of elements. For point labels that split into less number of values, we assume that those point labels are not valid (as we did encounter some spurious point label values during our testing) and hence infer `None` for the remaining values, and those rows with any null values are ultimately dropped during the preprocessing stage.

The code is glitching out as the configurations are not specified for the maximum number of splits possible on a point label (which is hence automatically treated as the legitimate kind of point label value).

Please let us know about your use cases with varied number of elements and the pre-processing steps you intend to achieve. We can accordingly try to address the same. Hope this helps.
